### ISSUE TITLE
启动报常量语法错误

### ISSUE THREAD

**Issue by yahahaff** [gomeplusFED/AMP#13]
/root/AMP/node_modules/koa/lib/response.js:47
    const { res } = this;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/root/AMP/node_modules/babel-core/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/AMP/node_modules/koa/lib/application.js:11:18)
    at Module._compile (module.js:409:26)

**Comment by luoye-fe** [comment]
node 版本的问题，使用最新版 node 就好

**Comment by yahahaff** [comment]
HI  
       非常感谢！ 我试试最新版 



729913331@qq.com
 
发件人： 骆也
发送时间： 2017-05-09 09:37
收件人： gomeplusFED/AMP
抄送： zhengJunhui; Author
主题： Re: [gomeplusFED/AMP] 启动报常量语法错误 (#13)
node 版本的问题，使用最新版 node 就好

**Comment by yahahaff** [comment]
Hi 打扰了 
      启动成功访问9090端口  报404
     没有views/index.production.html文件           
 
     希望能得到你的帮助！ 感谢
    


729913331@qq.com
 
发件人： 骆也
发送时间： 2017-05-09 09:37
收件人： gomeplusFED/AMP
抄送： zhengJunhui; Author
主题： Re: [gomeplusFED/AMP] 启动报常量语法错误 (#13)
node 版本的问题，使用最新版 node 就好

**Comment by luoye-fe** [comment]
**views/index.production.html** 这个文件是前端构建之后产出的，运行下 `npm run build` 进行前端生产环境构建

**Comment by yahahaff** [comment]
恩 已经正常使用   提升了我们公司的开发效率  由于对nodejs不熟悉，才会问这么低级的问题 非常感谢你的帮助 
                                                                   你的项目非常的nice！



729913331@qq.com
 
发件人： 骆也
发送时间： 2017-05-09 19:46
收件人： gomeplusFED/AMP
抄送： zhengJunhui; Author
主题： Re: [gomeplusFED/AMP] 启动报常量语法错误 (#13)
views/index.production.html 这个文件是前端构建之后产出的，运行下 npm run build 进行前端生产环境构建
