### ISSUE TITLE
注册过程中报错

### ISSUE THREAD

**Issue by heroWang** [gomeplusFED/AMP#4]
我点击注册后.后端报错,直接进程退出了.

/opt/node4.5/bin/node app.babel.js
http server listening on port 9090 ...
https server listening on port 8989 ...
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at delPassword (user.js:25:22)
    at user.js:129:35
    at /opt/AMP/node_modules/mongoose/lib/model.js:3324:16
    at /opt/AMP/node_modules/mongoose/lib/model.js:1858:15
    at /opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:726:13
    at /opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:52:16
    at done (/opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:241:17)
    at /opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:44:16
    at /opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:723:17
    at /opt/AMP/node_modules/mongoose/node_modules/async/lib/async.js:167:37
    at callbackWrapper (/opt/AMP/node_modules/mongoose/lib/model.js:1841:20)
    at handleError (/opt/AMP/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:40:22)
    at next_ (/opt/AMP/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:75:26)
    at fnWrapper (/opt/AMP/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:8)
    at /opt/AMP/node_modules/mongoose/lib/model.js:3324:16
    at /opt/AMP/node_modules/mongoose/lib/model.js:188:9
    at /opt/AMP/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

运行环境: 
mongodb 3.2.9
nodejs v4.5.0

**Comment by luoye-fe** [comment]
具体说一下流程呢？
检查下数据库连接是否正确

**Comment by heroWang** [comment]
数据库连接是正常的.
